// const table = document.querySelector("#table");
// const thead = document.querySelector(".table-body");
// const tbody = document.querySelector(".table-body");

const data = {
  currentMonth: "January",
  currentYear: 2025,
  totalDays: 31,
  assets: [
    {
      id: "asset_001",
      name: "JCB 3DX Backhoe Loader",
      model: "MH-12-AB-1234",
      category: "Backhoe Loader",
      location: "Site A - Pune",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "available" },
        { date: 3, dayName: "Fri", status: "selected" },
        { date: 4, dayName: "Sat", status: "selected" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "booked" },
        { date: 7, dayName: "Tue", status: "booked" },
        { date: 8, dayName: "Wed", status: "available" },
        { date: 9, dayName: "Thu", status: "available" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "booked" },
        { date: 14, dayName: "Tue", status: "selected" },
        { date: 15, dayName: "Wed", status: "available" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "booked" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 4,
    },
    {
      id: "asset_002",
      name: "Tata Hitachi ZX200 Excavator",
      model: "MH-12-CD-5678",
      category: "Excavator",
      location: "Site B - Mumbai",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "booked" },
        { date: 3, dayName: "Fri", status: "booked" },
        { date: 4, dayName: "Sat", status: "available" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "available" },
        { date: 7, dayName: "Tue", status: "available" },
        { date: 8, dayName: "Wed", status: "selected" },
        { date: 9, dayName: "Thu", status: "selected" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "available" },
        { date: 15, dayName: "Wed", status: "booked" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "available" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "booked" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 4,
    },
    {
      id: "asset_003",
      name: "Mahindra Earth Master",
      model: "MH-12-EF-9012",
      category: "Backhoe Loader",
      location: "Site C - Nashik",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "available" },
        { date: 3, dayName: "Fri", status: "selected" },
        { date: 4, dayName: "Sat", status: "selected" },
        { date: 5, dayName: "Sun", status: "selected" },
        { date: 6, dayName: "Mon", status: "available" },
        { date: 7, dayName: "Tue", status: "available" },
        { date: 8, dayName: "Wed", status: "available" },
        { date: 9, dayName: "Thu", status: "booked" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "available" },
        { date: 15, dayName: "Wed", status: "selected" },
        { date: 16, dayName: "Thu", status: "selected" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "available" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "booked" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 7,
    },
    {
      id: "asset_004",
      name: "JCB JS130 Excavator",
      model: "MH-12-GH-3456",
      category: "Excavator",
      location: "Site D - Thane",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "booked" },
        { date: 3, dayName: "Fri", status: "booked" },
        { date: 4, dayName: "Sat", status: "available" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "available" },
        { date: 7, dayName: "Tue", status: "available" },
        { date: 8, dayName: "Wed", status: "available" },
        { date: 9, dayName: "Thu", status: "available" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "selected" },
        { date: 15, dayName: "Wed", status: "selected" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "available" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 4,
    },
    {
      id: "asset_005",
      name: "CAT 320D Excavator",
      model: "MH-12-IJ-7890",
      category: "Excavator",
      location: "Site E - Nagpur",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "available" },
        { date: 3, dayName: "Fri", status: "available" },
        { date: 4, dayName: "Sat", status: "available" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "booked" },
        { date: 7, dayName: "Tue", status: "available" },
        { date: 8, dayName: "Wed", status: "available" },
        { date: 9, dayName: "Thu", status: "available" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "available" },
        { date: 15, dayName: "Wed", status: "available" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "booked" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 2,
    },
    {
      id: "asset_006",
      name: "Hyundai R140 Excavator",
      model: "MH-12-KL-2345",
      category: "Excavator",
      location: "Site F - Aurangabad",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "available" },
        { date: 3, dayName: "Fri", status: "available" },
        { date: 4, dayName: "Sat", status: "available" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "available" },
        { date: 7, dayName: "Tue", status: "available" },
        { date: 8, dayName: "Wed", status: "available" },
        { date: 9, dayName: "Thu", status: "available" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "available" },
        { date: 15, dayName: "Wed", status: "available" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "available" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 0,
    },
    {
      id: "asset_007",
      name: "Komatsu PC200 Excavator",
      model: "MH-14-MN-6789",
      category: "Excavator",
      location: "Site G - Solapur",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "booked" },
        { date: 2, dayName: "Thu", status: "booked" },
        { date: 3, dayName: "Fri", status: "booked" },
        { date: 4, dayName: "Sat", status: "available" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "available" },
        { date: 7, dayName: "Tue", status: "selected" },
        { date: 8, dayName: "Wed", status: "selected" },
        { date: 9, dayName: "Thu", status: "available" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "available" },
        { date: 15, dayName: "Wed", status: "booked" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "available" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 6,
    },
    {
      id: "asset_008",
      name: "Volvo EC210 Excavator",
      model: "MH-14-OP-4567",
      category: "Excavator",
      location: "Site A - Pune",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "available" },
        { date: 3, dayName: "Fri", status: "available" },
        { date: 4, dayName: "Sat", status: "selected" },
        { date: 5, dayName: "Sun", status: "selected" },
        { date: 6, dayName: "Mon", status: "selected" },
        { date: 7, dayName: "Tue", status: "available" },
        { date: 8, dayName: "Wed", status: "available" },
        { date: 9, dayName: "Thu", status: "booked" },
        { date: 10, dayName: "Fri", status: "booked" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "available" },
        { date: 15, dayName: "Wed", status: "available" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "booked" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "available" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 6,
    },
    {
      id: "asset_009",
      name: "CAT 320GC Excavator",
      model: "MH-14-QR-8901",
      category: "Excavator",
      location: "Site B - Mumbai",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "available" },
        { date: 3, dayName: "Fri", status: "available" },
        { date: 4, dayName: "Sat", status: "available" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "booked" },
        { date: 7, dayName: "Tue", status: "booked" },
        { date: 8, dayName: "Wed", status: "booked" },
        { date: 9, dayName: "Thu", status: "available" },
        { date: 10, dayName: "Fri", status: "available" },
        { date: 11, dayName: "Sat", status: "available" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "selected" },
        { date: 14, dayName: "Tue", status: "selected" },
        { date: 15, dayName: "Wed", status: "available" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "booked" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "available" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 6,
    },
    {
      id: "asset_010",
      name: "JCB 3CX Backhoe Loader",
      model: "MH-14-ST-2345",
      category: "Backhoe Loader",
      location: "Site C - Nashik",
      status: "active",
      days: [
        { date: 1, dayName: "Wed", status: "available" },
        { date: 2, dayName: "Thu", status: "selected" },
        { date: 3, dayName: "Fri", status: "selected" },
        { date: 4, dayName: "Sat", status: "selected" },
        { date: 5, dayName: "Sun", status: "available" },
        { date: 6, dayName: "Mon", status: "available" },
        { date: 7, dayName: "Tue", status: "available" },
        { date: 8, dayName: "Wed", status: "available" },
        { date: 9, dayName: "Thu", status: "available" },
        { date: 10, dayName: "Fri", status: "booked" },
        { date: 11, dayName: "Sat", status: "booked" },
        { date: 12, dayName: "Sun", status: "available" },
        { date: 13, dayName: "Mon", status: "available" },
        { date: 14, dayName: "Tue", status: "available" },
        { date: 15, dayName: "Wed", status: "available" },
        { date: 16, dayName: "Thu", status: "available" },
        { date: 17, dayName: "Fri", status: "available" },
        { date: 18, dayName: "Sat", status: "available" },
        { date: 19, dayName: "Sun", status: "available" },
        { date: 20, dayName: "Mon", status: "booked" },
        { date: 21, dayName: "Tue", status: "available" },
        { date: 22, dayName: "Wed", status: "available" },
        { date: 23, dayName: "Thu", status: "available" },
        { date: 24, dayName: "Fri", status: "available" },
        { date: 25, dayName: "Sat", status: "available" },
        { date: 26, dayName: "Sun", status: "available" },
        { date: 27, dayName: "Mon", status: "booked" },
        { date: 28, dayName: "Tue", status: "available" },
        { date: 29, dayName: "Wed", status: "available" },
        { date: 30, dayName: "Thu", status: "available" },
        { date: 31, dayName: "Fri", status: "available" },
      ],
      daysBooked: 7,
    },
  ],
};
// console.log(data);
// const currentMonth = document.querySelector(".current-month");
// const prev = document.querySelector(".prev");
// const next = document.querySelector(".next");

const now = new Date();

const customDate = new Date(2026, 0, 15, 0, 0, 0, 0);
const getMonth = new Date(customDate).getMonth();
const isoFormatDate = new Date("2025-01-15"); // 15 Jan
console.log(customDate);
console.log(getMonth);
console.log(isoFormatDate);

// seeting date
const setNewDate = new Date();

setNewDate.setFullYear(2026);
setNewDate.setMonth(0);
setNewDate.setDate(10);
console.log(setNewDate);
